# Generated by Django 4.0.3 on 2022-04-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='books_img',
            field=models.ImageField(default=None, upload_to='book/images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='books_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
